import type { Service } from "@/lib/types";

function slug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "service";
}

/**
 * A starting-point compose file for one host. Ports and volumes are guesses
 * from the catalogue — treat it as a skeleton to edit, not a finished stack.
 */
export function toCompose(hostLabel: string, services: Service[]): string {
  const withImages = services.filter((service) => service.image);
  const withoutImages = services.filter((service) => !service.image);

  const lines: string[] = [
    `# ${hostLabel} — generated by Homelab Planner`,
    "# Ports and volumes are starting points; check each project's own docs.",
    "",
  ];

  if (withImages.length === 0) {
    lines.push("# No containerised services assigned to this host.");
  } else {
    lines.push("services:");
    for (const service of withImages) {
      const name = slug(service.name);
      lines.push(`  ${name}:`);
      lines.push(`    image: ${service.image}`);
      lines.push(`    container_name: ${name}`);
      lines.push("    restart: unless-stopped");
      if (service.ports.length > 0) {
        lines.push("    ports:");
        for (const port of service.ports) lines.push(`      - "${port}:${port}"`);
      }
      lines.push("    volumes:");
      lines.push(`      - ./${name}/config:/config`);
      lines.push("    environment:");
      lines.push("      - TZ=Europe/London");
      lines.push("");
    }
  }

  if (withoutImages.length > 0) {
    lines.push("");
    lines.push("# Installed on the host rather than as a container:");
    for (const service of withoutImages) lines.push(`#   - ${service.name}`);
  }

  return lines.join("\n");
}

/** Ports requested by more than one service on the same host. */
export function portConflicts(services: Service[]): number[] {
  const seen = new Map<number, number>();
  for (const service of services) {
    for (const port of service.ports) seen.set(port, (seen.get(port) ?? 0) + 1);
  }
  return [...seen.entries()].filter(([, count]) => count > 1).map(([port]) => port).sort((a, b) => a - b);
}
