"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, Check, Copy, Network as NetworkIcon, Plus, Trash2 } from "lucide-react";
import { formatNumber, pluralise } from "@/lib/format";
import { newId } from "@/lib/id";
import { allRackItems, indexById, ipInSubnet, mergeDevices, parseCidr } from "@/lib/selectors";
import { usePlan } from "@/lib/store";
import type { Reservation, Subnet } from "@/lib/types";
import {
  Badge,
  Button,
  Card,
  EmptyState,
  Field,
  Modal,
  NumberInput,
  PageHeader,
  Select,
  Stat,
  TextInput,
  Textarea,
} from "@/components/ui";

export function Network() {
  const { plan, setPlan } = usePlan();
  const devices = useMemo(() => indexById(mergeDevices(plan.customDevices)), [plan.customDevices]);
  const rackItems = useMemo(() => allRackItems(plan, devices), [plan, devices]);
  const [hostsFileOpen, setHostsFileOpen] = useState(false);

  const duplicateIps = useMemo(() => {
    const counts = new Map<string, number>();
    for (const reservation of plan.reservations) {
      const key = reservation.ip.trim();
      if (key) counts.set(key, (counts.get(key) ?? 0) + 1);
    }
    return new Set([...counts.entries()].filter(([, count]) => count > 1).map(([ip]) => ip));
  }, [plan.reservations]);

  const totalHosts = plan.subnets.reduce((sum, subnet) => sum + (parseCidr(subnet.cidr)?.hosts ?? 0), 0);

  function addSubnet() {
    const subnet: Subnet = {
      id: newId("net"),
      name: "New VLAN",
      cidr: "192.168.0.0/24",
      vlanId: undefined,
      gateway: "",
    };
    setPlan((previous) => ({ ...previous, subnets: [...previous.subnets, subnet] }));
  }

  function updateSubnet(id: string, patch: Partial<Subnet>) {
    setPlan((previous) => ({
      ...previous,
      subnets: previous.subnets.map((subnet) => (subnet.id === id ? { ...subnet, ...patch } : subnet)),
    }));
  }

  function removeSubnet(id: string) {
    setPlan((previous) => ({
      ...previous,
      subnets: previous.subnets.filter((subnet) => subnet.id !== id),
      reservations: previous.reservations.filter((reservation) => reservation.subnetId !== id),
    }));
  }

  function addReservation() {
    if (plan.subnets.length === 0) return;
    const reservation: Reservation = {
      id: newId("res"),
      subnetId: plan.subnets[0].id,
      ip: "",
      hostname: "",
      rackItemId: null,
    };
    setPlan((previous) => ({ ...previous, reservations: [...previous.reservations, reservation] }));
  }

  function updateReservation(id: string, patch: Partial<Reservation>) {
    setPlan((previous) => ({
      ...previous,
      reservations: previous.reservations.map((reservation) =>
        reservation.id === id ? { ...reservation, ...patch } : reservation,
      ),
    }));
  }

  function removeReservation(id: string) {
    setPlan((previous) => ({
      ...previous,
      reservations: previous.reservations.filter((reservation) => reservation.id !== id),
    }));
  }

  const hostsFile = useMemo(() => {
    const lines = ["# Generated by Homelab Planner", ""];
    for (const subnet of plan.subnets) {
      const rows = plan.reservations.filter(
        (reservation) => reservation.subnetId === subnet.id && reservation.ip && reservation.hostname,
      );
      if (rows.length === 0) continue;
      lines.push(`# ${subnet.name} — ${subnet.cidr}`);
      const width = Math.max(...rows.map((row) => row.ip.length));
      for (const row of rows) lines.push(`${row.ip.padEnd(width)}  ${row.hostname}`);
      lines.push("");
    }
    return lines.join("\n");
  }, [plan.subnets, plan.reservations]);

  return (
    <>
      <PageHeader
        title="Network"
        description="Subnets, VLAN tags and the static addresses you have handed out — so you stop rediscovering them by nmap."
        actions={
          <div className="flex gap-2">
            <Button onClick={() => setHostsFileOpen(true)} disabled={plan.reservations.length === 0}>
              <Copy className="h-4 w-4" />
              Hosts file
            </Button>
            <Button variant="primary" onClick={addSubnet}>
              <Plus className="h-4 w-4" />
              Add subnet
            </Button>
          </div>
        }
      />

      <div className="grid gap-3 sm:grid-cols-3">
        <Stat label="Subnets" value={plan.subnets.length} icon={<NetworkIcon className="h-3.5 w-3.5" />} />
        <Stat label="Reservations" value={plan.reservations.length} hint={`${duplicateIps.size} duplicate address(es)`} tone={duplicateIps.size > 0 ? "danger" : "default"} />
        <Stat label="Addressable hosts" value={formatNumber(totalHosts, 0)} hint="Usable addresses across every subnet" />
      </div>

      <Card className="mt-4" title="Subnets" bodyClassName="p-0 sm:p-0">
        {plan.subnets.length === 0 ? (
          <div className="p-4">
            <EmptyState
              icon={<NetworkIcon className="h-8 w-8" />}
              title="No subnets yet"
              description="Add one per VLAN — trusted LAN, IoT, guest, cameras, management."
              action={
                <Button variant="primary" onClick={addSubnet}>
                  <Plus className="h-4 w-4" />
                  Add subnet
                </Button>
              }
            />
          </div>
        ) : (
          <div className="scroll-slim overflow-x-auto">
            <table className="w-full min-w-[48rem] text-left text-xs">
              <thead className="border-b border-edge text-[0.68rem] uppercase tracking-wider text-zinc-500">
                <tr>
                  <th className="px-4 py-2 font-medium">Name</th>
                  <th className="px-3 py-2 font-medium">CIDR</th>
                  <th className="px-3 py-2 font-medium">VLAN</th>
                  <th className="px-3 py-2 font-medium">Gateway</th>
                  <th className="px-3 py-2 text-right font-medium">Usable</th>
                  <th className="px-3 py-2 text-right font-medium">In use</th>
                  <th className="px-4 py-2" />
                </tr>
              </thead>
              <tbody className="divide-y divide-edge/70">
                {plan.subnets.map((subnet) => {
                  const parsed = parseCidr(subnet.cidr);
                  const used = plan.reservations.filter((r) => r.subnetId === subnet.id).length;
                  return (
                    <tr key={subnet.id} className="align-middle">
                      <td className="px-4 py-1.5">
                        <TextInput
                          value={subnet.name}
                          onChange={(event) => updateSubnet(subnet.id, { name: event.target.value })}
                          aria-label="Subnet name"
                          className="w-36"
                        />
                      </td>
                      <td className="px-3 py-1.5">
                        <TextInput
                          value={subnet.cidr}
                          onChange={(event) => updateSubnet(subnet.id, { cidr: event.target.value })}
                          aria-label="CIDR"
                          className={parsed ? "w-40 font-mono" : "w-40 font-mono border-rose-500/60"}
                        />
                      </td>
                      <td className="px-3 py-1.5">
                        <NumberInput
                          min={1}
                          max={4094}
                          value={subnet.vlanId ?? ""}
                          onChange={(event) =>
                            updateSubnet(subnet.id, {
                              vlanId:
                                event.target.value === ""
                                  ? undefined
                                  : Math.min(4094, Math.max(1, Number(event.target.value) || 1)),
                            })
                          }
                          aria-label="VLAN id"
                          className="w-20"
                        />
                      </td>
                      <td className="px-3 py-1.5">
                        <TextInput
                          value={subnet.gateway ?? ""}
                          onChange={(event) => updateSubnet(subnet.id, { gateway: event.target.value })}
                          aria-label="Gateway"
                          className="w-32 font-mono"
                        />
                      </td>
                      <td className="px-3 py-1.5 text-right font-mono text-zinc-400">
                        {parsed ? formatNumber(parsed.hosts, 0) : <Badge tone="over">invalid</Badge>}
                      </td>
                      <td className="px-3 py-1.5 text-right font-mono text-zinc-400">{used}</td>
                      <td className="px-4 py-1.5 text-right">
                        <Button variant="ghost" size="sm" aria-label={`Delete ${subnet.name}`} onClick={() => removeSubnet(subnet.id)}>
                          <Trash2 className="h-3.5 w-3.5" />
                        </Button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Card>

      <Card
        className="mt-4"
        title="Static addresses"
        description="Link an address to a device in the rack and the hostname follows it around."
        bodyClassName="p-0 sm:p-0"
        actions={
          <Button size="sm" onClick={addReservation} disabled={plan.subnets.length === 0}>
            <Plus className="h-3.5 w-3.5" />
            Add address
          </Button>
        }
      >
        {plan.reservations.length === 0 ? (
          <div className="p-4">
            <EmptyState
              title="No reservations yet"
              description={
                plan.subnets.length === 0
                  ? "Add a subnet first, then start pinning addresses to it."
                  : "Add the addresses you have already hard-coded into DHCP."
              }
            />
          </div>
        ) : (
          <div className="scroll-slim overflow-x-auto">
            <table className="w-full min-w-[52rem] text-left text-xs">
              <thead className="border-b border-edge text-[0.68rem] uppercase tracking-wider text-zinc-500">
                <tr>
                  <th className="px-4 py-2 font-medium">Address</th>
                  <th className="px-3 py-2 font-medium">Hostname</th>
                  <th className="px-3 py-2 font-medium">Subnet</th>
                  <th className="px-3 py-2 font-medium">Device</th>
                  <th className="px-3 py-2 font-medium">Notes</th>
                  <th className="px-4 py-2" />
                </tr>
              </thead>
              <tbody className="divide-y divide-edge/70">
                {plan.reservations.map((reservation) => {
                  const subnet = plan.subnets.find((entry) => entry.id === reservation.subnetId);
                  const outside = Boolean(
                    reservation.ip && subnet && !ipInSubnet(reservation.ip, subnet.cidr),
                  );
                  const duplicate = duplicateIps.has(reservation.ip.trim());

                  return (
                    <tr key={reservation.id} className="align-middle">
                      <td className="px-4 py-1.5">
                        <div className="flex items-center gap-1.5">
                          <TextInput
                            value={reservation.ip}
                            onChange={(event) => updateReservation(reservation.id, { ip: event.target.value })}
                            aria-label="IP address"
                            placeholder="192.168.1.50"
                            className={
                              outside || duplicate ? "w-32 border-rose-500/60 font-mono" : "w-32 font-mono"
                            }
                          />
                          {(outside || duplicate) && (
                            <span
                              title={duplicate ? "Used more than once" : `Outside ${subnet?.cidr}`}
                              className="text-rose-400"
                            >
                              <AlertTriangle className="h-3.5 w-3.5" />
                            </span>
                          )}
                        </div>
                      </td>
                      <td className="px-3 py-1.5">
                        <TextInput
                          value={reservation.hostname}
                          onChange={(event) => updateReservation(reservation.id, { hostname: event.target.value })}
                          aria-label="Hostname"
                          className="w-32"
                        />
                      </td>
                      <td className="px-3 py-1.5">
                        <Select
                          value={reservation.subnetId}
                          onChange={(event) => updateReservation(reservation.id, { subnetId: event.target.value })}
                          aria-label="Subnet"
                          className="w-32"
                        >
                          {plan.subnets.map((entry) => (
                            <option key={entry.id} value={entry.id}>
                              {entry.name}
                            </option>
                          ))}
                        </Select>
                      </td>
                      <td className="px-3 py-1.5">
                        <Select
                          value={reservation.rackItemId ?? ""}
                          onChange={(event) =>
                            updateReservation(reservation.id, { rackItemId: event.target.value || null })
                          }
                          aria-label="Linked device"
                          className="w-40"
                        >
                          <option value="">—</option>
                          {rackItems.map((entry) => (
                            <option key={entry.item.id} value={entry.item.id}>
                              {entry.label}
                            </option>
                          ))}
                        </Select>
                      </td>
                      <td className="px-3 py-1.5">
                        <TextInput
                          value={reservation.notes ?? ""}
                          onChange={(event) => updateReservation(reservation.id, { notes: event.target.value })}
                          aria-label="Notes"
                          className="w-40"
                        />
                      </td>
                      <td className="px-4 py-1.5 text-right">
                        <Button
                          variant="ghost"
                          size="sm"
                          aria-label={`Delete ${reservation.hostname || reservation.ip}`}
                          onClick={() => removeReservation(reservation.id)}
                        >
                          <Trash2 className="h-3.5 w-3.5" />
                        </Button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </Card>

      {plan.subnets.length > 0 && (
        <Card className="mt-4" title="Subnet notes">
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {plan.subnets.map((subnet) => (
              <Field key={subnet.id} label={`${subnet.name} — ${pluralise(plan.reservations.filter((r) => r.subnetId === subnet.id).length, "address", "addresses")}`}>
                {(id) => (
                  <Textarea
                    id={id}
                    rows={2}
                    value={subnet.notes ?? ""}
                    onChange={(event) => updateSubnet(subnet.id, { notes: event.target.value })}
                    placeholder="Firewall rules, what lives here…"
                  />
                )}
              </Field>
            ))}
          </div>
        </Card>
      )}

      <HostsFileModal open={hostsFileOpen} onClose={() => setHostsFileOpen(false)} content={hostsFile} />
    </>
  );
}

function HostsFileModal({
  open,
  onClose,
  content,
}: {
  open: boolean;
  onClose: () => void;
  content: string;
}) {
  const [copied, setCopied] = useState(false);

  async function copy() {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2000);
    } catch {
      setCopied(false);
    }
  }

  return (
    <Modal
      open={open}
      onClose={onClose}
      wide
      title="Hosts file"
      description="Paste into /etc/hosts, or use it as the source of truth for your DNS entries."
      footer={
        <>
          <Button onClick={onClose}>Close</Button>
          <Button variant="primary" onClick={copy}>
            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
            {copied ? "Copied" : "Copy"}
          </Button>
        </>
      }
    >
      <pre className="scroll-slim overflow-x-auto rounded-lg border border-edge bg-canvas px-3 py-2.5 font-mono text-[0.7rem] leading-relaxed text-zinc-300">
        {content}
      </pre>
    </Modal>
  );
}
